name: Build docker image
on:
  push:
    branches: [ "main" ]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@v4
      - name: build the docker image
        run: docker build . --tag guestbookinmemory:$(date +%s)
      
